### ISSUE TITLE
Weighted sum check is incorrect for some BSNs

### ISSUE THREAD

**Issue by javanegmond** [MrLuit/elfproef#1]
The check on the weighted sum for your elfproef is incorrect for BSNs. The check `sum > 0` makes it so some valid BSNs do not pass this elfproef implementation.

For example:
```
const valid = validateBSN("100000009");
// Expected value: valid = true
// your implementation value: valid = false
```

Some background:
This is a common mistake, likely originating from the world of banking. In the (Dutch) banking world, account numbers also use the elfproef, except the weight for the last digit is 1 and not -1 as it is for BSNs. Since a bank account cannot be all zeros, the `sum > 0` validation is often added.
However, due to the -1 weight of the last digit in BSNs, a valid BSN can have a weighted sum of 0. BSNs can have a maximum of 1 leading zero, when padded to a full length of 9, which also eliminates the use of BSN '000000000'. However, care should be taken that a lot of test sets of BSNs use BSNs with more leading zeros. These BSNs are never issued and as such are safe to use in test environments, without ever colliding with a real issued BSN.

**Comment by MrLuit** [comment]
Hi, thanks for the feedback. I fixed this issue in #2 and published a new version which includes more tests to make sure results are accurate.

Please let me know if you find any other issues :)
